/* GENERATED by scripts/extract-templates.mjs from document-automation/power-of-attorney.html — do not edit here;
   the source is document-automation/_build/power-of-attorney/pwa-engine.js. */
/* หนังสือมอบอำนาจให้ฟ้องคดี — the fill engine.
   One file, run as it is by the page (inlined by assemble.py) and by the MCP
   server (copied to mcp-server/src/pwa-engine.cjs by `npm run sync-templates`),
   so a document made in either place is the same document.

   Three forms (S.form):
     "th"     the firm's current Thai form (September 2026) — the default
     "thEn"   the same, Thai and English paragraph by paragraph
     "legacy" the 2024 form (eight clauses, courts and a defined term)
   D = the build's data: { frags, alt, geom, tpl } for "legacy" (build_pwa.py,
   measure.py) and D.forms.th / D.forms.thEn the same for the current forms
   (build_new.py, measure_new.py).
   S = the page's state (blankState). fromInput() maps the MCP's English keys.

   Filling never builds formatting of its own. Each value is typed into the
   run that held the old value: the run keeps its <w:rPr>, and only <w:cs/> is
   set per stretch of text the way Word sets it when you type — on Thai, off on
   Latin letters and digits, spaces and punctuation staying with their
   neighbours. Paragraphs and table rows are the precedents' own, copied whole. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.PWAEngine = factory();
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const MONTHS = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน',
                  'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];
  const THD = '๐๑๒๓๔๕๖๗๘๙';

  /* The fixed words the tool writes when it composes a value itself. They are
     the precedents' own wording (the company and individual files), with one
     spelling fixed in the forum sentence: "องค์กรณ์" → "องค์กร". */
  const W_ = {
    incorporation: 'นิติบุคคลจัดตั้งขึ้นถูกต้องตามกฎหมายแห่งราชอาณาจักรไทย',
    authority: 'กรรมการผู้มีอำนาจลงลายมือชื่อและประทับตราสำคัญกระทำการแทนได้',
    regNo: 'ทะเบียนนิติบุคคลเลขที่',
    office: 'สำนักงานแห่งใหญ่ตั้งอยู่ ณ',
    domicile: 'ภูมิลำเนาอยู่ ณ',
    idCard: 'บัตรประจำตัวประชาชนเลขที่',
    passport: 'หนังสือเดินทางเลขที่',
    dirId: 'ผู้ถือบัตรประจำตัวประชาชนเลขที่',
    forumTail: 'ศาลสถิตยุติธรรมที่มีเขตอำนาจ องค์กร หน่วยงานของรัฐ และ/หรือ พนักงานเจ้าหน้าที่ตลอดจนบุคคลที่เกี่ยวข้องอื่นใด',
    because: 'อันเนื่องมาจาก',
    grantorLabel: 'ผู้มอบอำนาจ',
    attorneyLabel: 'ผู้รับมอบอำนาจ',
    witnessLabel: 'พยาน'
  };

  /* The words the tool writes itself in the current forms ("th", "thEn"): the
     precedents' own, for a company; for a person, the 2024 form's Thai and the
     Thai–English form's own English terms. The place is the firm's office, which
     both precedents print after "ทำที่". */
  const W2 = {
    entity: 'นิติบุคคลประเภทบริษัทจำกัด จดทะเบียนขึ้นตามกฎหมายแห่งราชอาณาจักรไทย',
    entityPublic: 'นิติบุคคลประเภทบริษัทมหาชนจำกัด จดทะเบียนขึ้นตามกฎหมายแห่งราชอาณาจักรไทย',
    entityEn: 'a limited company incorporated under the laws of the Kingdom of Thailand',
    entityPublicEn: 'a public limited company incorporated under the laws of the Kingdom of Thailand',
    office: 'สำนักงานใหญ่ตั้งอยู่',
    officeEn: 'with its head office at',
    self: 'ข้าพเจ้า',
    idCardEn: 'Thai Identification No.', passportEn: 'Passport No.',
    holderEn: 'holder of', residingEn: 'residing at',
    action: 'ฟ้องร้องดำเนินคดีทั้งทางแพ่งและอาญากับ',
    actionEn: 'to institute and conduct both civil and criminal proceedings against',
    place: '89 อาคารเอไอเอ แคปปิตอล เซ็นเตอร์ ชั้น 15 ห้องเลขที่ 1507 ถนนรัชดาภิเษก \nแขวงดินแดง เขตดินแดง กรุงเทพมหานคร',
    placeEn: 'No. 89 AIA Capital Center Building, \n15th Floor, Room No. 1507, Ratchadaphisek Rd., \nDin Daeng, Din Daeng, Bangkok',
    grantorLabelEn: 'Principal', attorneyLabelEn: 'Attorney-in-Fact', witnessLabelEn: 'Witness'
  };
  const MONTHS_EN = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
                     'October', 'November', 'December'];
  const PLACEHOLDER = '(*)';

  /* The six powers of the current forms, as printed (summaries for the page and reports). */
  const CLAUSES_NEW = [
    'ยื่นคำฟ้อง คำร้อง คำคู่ความ แต่งตั้งทนายความ ดำเนินกระบวนพิจารณา จำหน่ายสิทธิ จนถึงชั้นบังคับคดี …',
    'ทำ ลงนาม และรับรองคำแปลภาษาไทย รับรองสำเนา ส่งมอบเอกสาร …',
    'เข้าร่วมการเจรจา ไกล่เกลี่ย ประนีประนอมยอมความ …',
    'ให้การ เป็นพยาน ร้องเรียน ต่อหน่วยงานรัฐ อัยการ พนักงานสอบสวน พนักงานปกครอง และขอคัดเอกสารทางทะเบียน …',
    'กระทำการในเรื่องใดๆ ทั้งหมดที่จำเป็นหรือเหมาะสม …',
    'แต่งตั้งผู้รับมอบอำนาจช่วง …'
  ];

  /* The clauses printed on every document, in order; text as in the template
     (the tool never edits them). Used for the page's list and for reports. */
  const CLAUSES = [
    'ยื่นฟ้องและดำเนินคดีแพ่งและอาญากับคู่กรณีต่อศาล …',
    'เข้าร่วมและดำเนินกระบวนพิจารณาคดีของศาล …',
    'แต่งตั้งทนายความ (มาตรา 62) …',
    'ทำ ลงนาม และรับรองคำแปลภาษาไทย …',
    'เข้าร่วมการเจรจา ไกล่เกลี่ย ประนีประนอมยอมความ …',
    'ให้การ เป็นพยาน ให้ถ้อยคำ … ที่เกี่ยวกับ(เหตุ) …',
    'กระทำการในเรื่องใดๆ ทั้งหมดที่จำเป็นหรือเหมาะสม …',
    'แต่งตั้งผู้รับมอบอำนาจช่วง …'
  ];

  const BLANK_NAME = '______________________________';

  const FORMS = {
    th: { name: 'แบบปัจจุบัน — ภาษาไทย', clauses: CLAUSES_NEW, bilingual: false },
    thEn: { name: 'แบบปัจจุบัน — ไทย/อังกฤษ', clauses: CLAUSES_NEW, bilingual: true },
    legacy: { name: 'แบบเดิม (2567)', clauses: CLAUSES, bilingual: false }
  };
  const isNew = S => S.form !== 'legacy';
  /* "th-en", "bilingual", "2024" … → the form's key. */
  function formKey(f) {
    const k = String(f == null ? '' : f).trim();
    if (FORMS[k]) return k;
    if (/en|eng|bi|อังกฤษ/i.test(k)) return 'thEn';
    if (/legacy|old|2024|2567|เดิม/i.test(k)) return 'legacy';
    return 'th';
  }

  /* ── Text helpers ───────────────────────────────────────────── */
  const norm = s => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
  /* Free text keeps the drafter's own line breaks (a Thai justified line is often
     mended with one) and the space before them; only doubled spaces and the
     spaces at either end go. */
  const normText = s => String(s == null ? '' : s).replace(/\r\n?/g, '\n').replace(/[ \u00A0\t]+/g, ' ').replace(/^ +| +$/g, '');
  /* The space before a value is the precedent's own run and stays; the one
     after is typed with the value — except after a line break, where the
     drafter wanted the line to end. */
  const sp = v => v && v[v.length - 1] !== '\n' ? v + ' ' : v;
  const toArab = s => String(s || '').replace(/[๐-๙]/g, c => String(THD.indexOf(c)));
  const digits = s => toArab(s).replace(/\D/g, '');
  const isPlaceholder = v => /^\(\*.*\)$/.test(String(v == null ? '' : v).trim());

  function fmtId(s) {
    const d = digits(s);
    if (d.length !== 13) return norm(s);
    return [d[0], d.slice(1, 5), d.slice(5, 10), d.slice(10, 12), d[12]].join(' ');
  }
  function idValid(s) {
    const d = digits(s);
    if (d.length !== 13) return false;
    let t = 0; for (let i = 0; i < 12; i++) t += (+d[i]) * (13 - i);
    return (11 - t % 11) % 10 === +d[12];
  }
  function thaiDate(iso) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(iso || '')) return '';
    const [y, m, d] = iso.split('-').map(Number);
    return d + ' ' + MONTHS[m - 1] + ' ' + (y + 543);
  }
  function englishDate(iso) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(iso || '')) return '';
    const [y, m, d] = iso.split('-').map(Number);
    return d + ' ' + MONTHS_EN[m - 1] + ' ' + y;
  }
  const withNo = a => (a = norm(a)) && !/^เลขที่/.test(a) ? 'เลขที่ ' + a : a;
  const withNoEn = a => (a = norm(a)) && /^\d/.test(a) ? 'No. ' + a : a;
  const need = v => v ? v : PLACEHOLDER;
  const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const put = (xml, mark, s) => xml.split(mark).join(s);

  /* ── Typing into a run ──────────────────────────────────────── */
  const isThai = c => c >= '฀' && c <= '๿';
  const isLatin = c => /[A-Za-z0-9À-ɏ]/.test(c);

  /* Stretches of one script. Spaces and punctuation belong to the stretch they
     sit in (leading ones to the first script after them), as Word does. A
     stretch with no Thai or Latin at all keeps the run exactly as it was. */
  function scriptChunks(text) {
    const out = [];
    let cur = null;
    for (const ch of text) {
      const k = isThai(ch) ? 'T' : isLatin(ch) ? 'L' : null;
      if (!cur) { cur = { k, s: ch }; out.push(cur); continue; }
      if (k === null || k === cur.k) { cur.s += ch; continue; }
      if (cur.k === null) { cur.k = k; cur.s += ch; continue; }
      cur = { k, s: ch }; out.push(cur);
    }
    return out;
  }

  const RPR_AFTER_CS = /<w:(?:em|lang|eastAsianLayout|specVanish|oMath)\b/;
  const RPR_AFTER_HL = /<w:(?:u|effect|bdr|shd|fitText|vertAlign|rtl|cs|em|lang|eastAsianLayout|specVanish|oMath)\b/;
  function insertAt(inner, re, el) {
    const i = inner.search(re);
    return i < 0 ? inner + el : inner.slice(0, i) + el + inner.slice(i);
  }
  function adjustRpr(rpr, script, highlight) {
    if (script === null && !highlight) return rpr;
    let inner = rpr ? rpr.replace(/^<w:rPr>/, '').replace(/<\/w:rPr>$/, '') : '';
    if (script !== null) {
      inner = inner.replace(/<w:cs(?: w:val="[^"]*")?\/>/g, '');
      if (script === 'T') inner = insertAt(inner, RPR_AFTER_CS, '<w:cs/>');
    }
    if (highlight && !/<w:highlight\b/.test(inner)) inner = insertAt(inner, RPR_AFTER_HL, '<w:highlight w:val="yellow"/>');
    return inner ? '<w:rPr>' + inner + '</w:rPr>' : '';
  }
  function content(s) {
    let out = '', buf = '';
    const flush = () => { if (buf) { out += '<w:t xml:space="preserve">' + esc(buf) + '</w:t>'; buf = ''; } };
    for (const ch of s) {
      if (ch === '\n') { flush(); out += '<w:br/>'; }
      else if (ch === '\t') { flush(); out += '<w:tab/>'; }
      else buf += ch;
    }
    flush();
    return out;
  }
  function typeRuns(open, rpr, text, highlight) {
    return scriptChunks(text).map(c => open + adjustRpr(rpr, c.k, highlight) + content(c.s) + '</w:r>').join('');
  }

  /* Replace the run holding ⟦id⟧ with the value typed into it. A value is a
     string, or a list of { text, alt } where alt picks the other run properties
     the build kept for this marker (the grantor's name in bold). An empty
     value removes the run. "(*…)" marks a deliberate blank: highlighted. */
  let MARK = false;       // preview only: typed runs carry data-v="1" so the page can show them
  function fill(xml, id, value, altRpr) {
    const mark = '⟦' + id + '⟧';
    let i;
    while ((i = xml.indexOf(mark)) !== -1) {
      const s = Math.max(xml.lastIndexOf('<w:r>', i), xml.lastIndexOf('<w:r ', i));
      const e = xml.indexOf('</w:r>', i) + 6;
      const run = xml.slice(s, e);
      const open = MARK ? '<w:r data-v="1">' : run.slice(0, run.indexOf('>') + 1);
      const m = run.match(/<w:rPr>[\s\S]*?<\/w:rPr>/);
      const rpr = m ? m[0] : '';
      const segs = Array.isArray(value) ? value : [{ text: value }];
      const out = segs.map(g => {
        const t = String(g.text == null ? '' : g.text);
        return typeRuns(open, g.alt ? altRpr : rpr, t, isPlaceholder(g.ph != null ? g.ph : t));
      }).join('');
      xml = xml.slice(0, s) + out + xml.slice(e);
    }
    return xml;
  }

  /* ── State ──────────────────────────────────────────────────── */
  /* English fields (…En) are used by the Thai–English form only; a null "auto"
     field (place, sigNewPage, entity …) takes the form's own default. */
  const blankPerson = () => ({ name: '', idType: 'id', idNo: '', address: '', detail: null, nameEn: '', addressEn: '', detailEn: null });
  const blankDirector = () => ({ name: '', idNo: '', nameEn: '' });
  const blankAttorney = () => ({ name: '', idNo: '', nameEn: '' });
  function blankState() {
    return {
      kind: 'litigation',
      form: 'th',
      matter: '',
      place: null, placeEn: null, dateIso: '', dateText: null, dateTextEn: null,
      grantor: {
        type: 'company',
        company: { name: '', incorporation: W_.incorporation, regNo: '', address: '',
                   directors: [blankDirector()], directorIds: false, authority: W_.authority, detail: null,
                   nameEn: '', addressEn: '', entity: null, entityEn: null, detailEn: null },
        persons: [blankPerson()],
        capacity: '', capacityEn: ''
      },
      attorneys: [blankAttorney()],
      facts: { counterparty: '', forums: [''], bodies: [], cause: '', term: '', claim: null, court: null,
               counterpartyEn: '', causeEn: '', action: null, actionEn: null },
      extraClauses: [],
      witnesses: ['', ''], witnessesEn: [],
      sigNewPage: null,
      stamp: { principals: null, amount: null }
    };
  }
  function adoptState(st) {
    st = st || {};
    const b = blankState();
    const g = st.grantor || {};
    /* A state saved before the current forms existed has no form: it opens in the
       current Thai form, its blank "ทำที่" becoming the form's default place. */
    if (st.form == null && st.place === '') st = Object.assign({}, st, { place: null });
    const out = Object.assign(b, st);
    out.form = FORMS[st.form] ? st.form : 'th';
    out.grantor = Object.assign(blankState().grantor, g);
    out.grantor.company = Object.assign(blankState().grantor.company, g.company || {});
    out.grantor.company.directors = (out.grantor.company.directors && out.grantor.company.directors.length
      ? out.grantor.company.directors : [blankDirector()]).map(d => Object.assign(blankDirector(), d));
    out.grantor.persons = (g.persons && g.persons.length ? g.persons : [blankPerson()]).map(p => Object.assign(blankPerson(), p));
    if (out.grantor.type !== 'individual') out.grantor.type = 'company';
    out.attorneys = (st.attorneys && st.attorneys.length ? st.attorneys : [blankAttorney()]).map(a => Object.assign(blankAttorney(), a));
    out.facts = Object.assign(blankState().facts, st.facts || {});
    if (!Array.isArray(out.facts.forums) || !out.facts.forums.length) out.facts.forums = [''];
    if (!Array.isArray(out.facts.bodies)) out.facts.bodies = [];
    out.extraClauses = (st.extraClauses || []).map(c => ({ after: clampAfter(c.after, out.form), text: c.text || '', textEn: c.textEn || '' }));
    out.witnesses = Array.isArray(st.witnesses) ? st.witnesses.map(w => w || '') : ['', ''];
    out.witnessesEn = Array.isArray(st.witnessesEn) ? st.witnessesEn.map(w => w || '') : [];
    out.stamp = Object.assign(blankState().stamp, st.stamp || {});
    out.sigNewPage = st.sigNewPage == null ? null : st.sigNewPage !== false;
    return out;
  }
  const clampAfter = (n, form) => Math.max(0, Math.min(FORMS[form || 'legacy'].clauses.length, parseInt(n, 10) || 0));
  /* Signatures on a new page: the 2024 form and the Thai–English form do it
     (their precedents carry the note); the Thai form signs straight on. */
  const sigNewPage = S => S.sigNewPage != null ? !!S.sigNewPage : S.form !== 'th';

  /* The MCP's English keys → state. Absent means "compose it"; "" means blank. */
  function fromInput(a) {
    a = a || {};
    const S = blankState();
    const g = a.grantor || {};
    S.form = formKey(a.form);
    S.matter = a.matter || '';
    /* "ทำที่": absent → the form's default (the 2024 form: blank); "" → blank. */
    S.place = a.place != null ? String(a.place) : S.form === 'legacy' ? '' : null;
    if (a.placeEn != null) S.placeEn = String(a.placeEn);
    S.dateIso = a.date || '';
    if (a.dateText != null) S.dateText = a.dateText;
    S.grantor.type = g.type === 'individual' ? 'individual' : 'company';
    if (g.company) {
      const c = g.company, T = S.grantor.company;
      T.name = c.name || '';
      if (c.incorporation != null) T.incorporation = c.incorporation;
      T.regNo = c.registrationNumber || '';
      T.address = c.headOfficeAddress || '';
      if (c.directors && c.directors.length) T.directors = c.directors.map(d => ({ name: d.name || '', idNo: d.idNumber || '' }));
      T.directorIds = !!(c.directors || []).some(d => d.idNumber);
      if (c.authorityWording != null) T.authority = c.authorityWording;
      if (c.descriptionOverride != null) T.detail = c.descriptionOverride;
      T.nameEn = c.nameEn || '';
      T.addressEn = c.headOfficeAddressEn || '';
      if (c.entityWording != null) T.entity = c.entityWording;
      if (c.entityWordingEn != null) T.entityEn = c.entityWordingEn;
      if (c.descriptionOverrideEn != null) T.detailEn = c.descriptionOverrideEn;
      if (c.directors && c.directors.length) c.directors.forEach((d, i) => { T.directors[i].nameEn = d.nameEn || ''; });
    }
    if (g.persons && g.persons.length) {
      S.grantor.persons = g.persons.map(p => ({ name: p.name || '', idType: /pass/i.test(p.idType || '') ? 'passport' : 'id',
        idNo: p.idNumber || '', address: p.address || '', detail: p.descriptionOverride != null ? p.descriptionOverride : null,
        nameEn: p.nameEn || '', addressEn: p.addressEn || '', detailEn: p.descriptionOverrideEn != null ? p.descriptionOverrideEn : null }));
    }
    S.grantor.capacity = g.capacity || '';
    S.grantor.capacityEn = g.capacityEn || '';
    if (a.attorneys && a.attorneys.length) S.attorneys = a.attorneys.map(x => ({ name: x.name || '', idNo: x.idNumber || '', nameEn: x.nameEn || '' }));
    const f = a.matterFacts || {};
    S.facts.counterparty = f.counterparty || '';
    S.facts.counterpartyEn = f.counterpartyEn || '';
    S.facts.causeEn = f.causeEn || '';
    if (f.actionOverride != null) S.facts.action = f.actionOverride;
    if (f.actionOverrideEn != null) S.facts.actionEn = f.actionOverrideEn;
    S.facts.forums = f.courts && f.courts.length ? f.courts.slice() : [''];
    S.facts.bodies = f.otherBodies ? f.otherBodies.slice() : [];
    S.facts.cause = f.cause || '';
    S.facts.term = f.definedTerm || '';
    if (f.narrativeOverride != null) S.facts.claim = f.narrativeOverride;
    if (f.clause1CourtsOverride != null) S.facts.court = f.clause1CourtsOverride;
    S.extraClauses = (a.extraClauses || []).map(c => ({ after: clampAfter(c.afterClause, S.form), text: c.text || '', textEn: c.textEn || '' }));
    if (Array.isArray(a.witnesses)) {
      S.witnesses = a.witnesses.map(w => (w && typeof w === 'object' ? w.name : w) || '');
      S.witnessesEn = a.witnesses.map(w => (w && typeof w === 'object' ? w.nameEn : '') || '');
    }
    /* What the 2024 form reads and the current forms do not: told, not silently dropped. */
    const notes = [];
    if (S.form !== 'legacy') {
      const used = ['courts', 'otherBodies', 'definedTerm', 'narrativeOverride', 'clause1CourtsOverride']
        .filter(k => f[k] != null && !(Array.isArray(f[k]) && !f[k].filter(Boolean).length) && String(f[k]).trim() !== '');
      if (used.length) notes.push('matterFacts.' + used.join(', matterFacts.') + ' — used only by form "legacy" (2024); the current form reads "ต่อศาลยุติธรรมที่มีเขตอำนาจ" and calls the cause (“ข้อพิพาท”). Not printed.');
      if (g.company && (g.company.registrationNumber || g.company.authorityWording || g.company.incorporation))
        notes.push('grantor.company.registrationNumber / authorityWording / incorporation — the current form does not print them (it names the company, its kind and its head office). Not printed.');
    }
    S.inputNotes = notes;
    if (a.signaturesOnNextPage != null) S.sigNewPage = !!a.signaturesOnNextPage;
    if (a.stampDuty) {
      if (a.stampDuty.principals != null) S.stamp.principals = a.stampDuty.principals;
      if (a.stampDuty.amountOverride != null) S.stamp.amount = a.stampDuty.amountOverride;
    }
    return adoptState(S);
  }

  /* ── What the document says, worked out from the state ──────── */
  function companyDetail(c) {
    if (c.detail != null) return normText(c.detail);
    const dirs = c.directors.filter(d => norm(d.name));
    const who = dirs.map(d => norm(d.name) + (c.directorIds && norm(d.idNo) ? ' ' + W_.dirId + ' ' + fmtId(d.idNo) : '')).join(' และ');
    return [
      norm(c.incorporation),
      norm(c.regNo) && W_.regNo + ' ' + norm(c.regNo),
      norm(c.address) && W_.office + ' ' + withNo(c.address),
      who && 'โดย' + who + (norm(c.authority) ? ' ' + norm(c.authority) : '')
    ].filter(Boolean).join(' ');
  }
  function personDetail(p) {
    if (p.detail != null) return normText(p.detail);
    return [
      norm(p.idNo) && (p.idType === 'passport' ? W_.passport : W_.idCard) + ' ' + fmtId(p.idNo),
      norm(p.address) && W_.domicile + ' ' + withNo(p.address)
    ].filter(Boolean).join(' ');
  }
  function claimAuto(f) {
    const where = f.forums.concat(f.bodies).map(norm).filter(Boolean);
    return 'ต่อ' + (where.length ? where.join(' ') + ' หรือ' : '') + W_.forumTail + ' ' + W_.because + normText(f.cause);
  }
  const courtAuto = f => f.forums.map(norm).filter(Boolean).join(' ').replace(/^ศาล\s*/, '');

  function stampDuty(S) {
    const n = Math.max(1, S.attorneys.length);
    const autoP = S.grantor.type === 'individual' ? Math.max(1, S.grantor.persons.filter(p => norm(p.name)).length || 1) : 1;
    const principals = S.stamp.principals != null && S.stamp.principals !== '' ? Math.max(1, parseInt(S.stamp.principals, 10) || 1) : autoP;
    const auto = 30 * n * principals;
    const amt = S.stamp.amount != null && String(S.stamp.amount).trim() !== '' ? String(S.stamp.amount).trim() : null;
    return {
      item: n > 1 ? '7(ค)' : '7(ข)',
      attorneys: n, principals, principalsAuto: S.stamp.principals == null || S.stamp.principals === '',
      perPerson: 30, auto,
      amount: amt != null ? amt : String(auto), overridden: amt != null
    };
  }

  function derive(S) {
    if (isNew(S)) return deriveNew(S);
    const g = S.grantor, f = S.facts, V = {};
    V.place = normText(S.place);
    V.date = S.dateText != null ? norm(S.dateText) : thaiDate(S.dateIso);
    if (g.type === 'company') {
      const c = g.company;
      const d = companyDetail(c);
      /* The company precedent types the space after the name in bold. */
      V.grantorSegs = [{ text: norm(c.name) && d ? norm(c.name) + ' ' : norm(c.name), alt: true }, { text: d }];
      V.companyName = norm(c.name);
      V.grantorSigners = c.directors.map(d => norm(d.name));
    } else {
      const ps = g.persons;
      V.grantorSegs = [];
      ps.forEach((p, i) => {
        V.grantorSegs.push({ text: norm(p.name), alt: true });
        const d = personDetail(p);
        V.grantorSegs.push({ text: (d ? ' ' + d : '') + (i < ps.length - 1 ? ' และ' : '') });
      });
      V.tail = sp(normText(g.capacity));
      V.grantorSigners = ps.map(p => norm(p.name));
    }
    V.attorneys = S.attorneys.map(a => ({ name: norm(a.name), id: fmtId(a.idNo) }));
    V.counterparty = norm(f.counterparty);
    V.claim = f.claim != null ? normText(f.claim) : claimAuto(f);
    V.court = f.court != null ? norm(f.court).replace(/^ศาล\s*/, '') : courtAuto(f);
    V.term = norm(f.term);
    V.stamp = stampDuty(S);
    return V;
  }

  /* ── The signature table ────────────────────────────────────── */
  /* Rows of two, one signer per half; an odd one out gets the full width,
     centred — how every precedent lays it out. A lone grantor sits alone at
     the top (a company's name above its director). Two blank lines before the
     first attorneys' row, one after every row, as in the precedents. */
  function sigRows(F, S, V) {
    const s = F.sig, rows = [];
    const cell = (full, ps) => '<w:tc>' + (full ? F.tcFull : F.tcHalf) + ps.join('') + '</w:tc>';
    const row = cells => F.tr + cells.join('') + '</w:tr>';
    const nm = (p, n) => fill(p, 'name', n || BLANK_NAME);
    const lab = (p, l) => put(p, '⟦label⟧', l);                 // a fixed word, in the run that held it
    const rep = (p, k) => Array.from({ length: k }, () => p);
    function block(names, label, firstLead) {
      for (let i = 0; i < names.length; i += 2) {
        const lead = i === 0 ? firstLead : 0;
        if (i + 1 < names.length) {
          rows.push(row([0, 1].map(j => cell(false,
            rep(s['H.blank'], lead).concat([lab(s['H.sig'], label), nm(s['H.name'], names[i + j]), s['H.trail']])))));
        } else {
          rows.push(row([cell(true,
            rep(s['F.trail'], lead).concat([lab(s['F.sig'], label), nm(s['F.name'], names[i]), s['F.trail']]))]));
        }
      }
    }
    const signers = V.grantorSigners.length ? V.grantorSigners : [''];
    if (S.grantor.type === 'company') {
      const co = fill(s['GC.company'], 'company', V.companyName);
      if (signers.length === 1) rows.push(row([cell(true, [co, s['GC.blank'], s['GC.blank'], s['GC.sig'], nm(s['GC.name'], signers[0])])]));
      else { rows.push(row([cell(true, [co])])); block(signers, W_.grantorLabel, 2); }
    } else if (signers.length === 1) {
      rows.push(row([cell(true, [s['GI.blank'], s['GI.sig'], nm(s['GI.name'], signers[0])])]));
    } else block(signers, W_.grantorLabel, 1);
    /* Blank lines above the attorneys: one after a company's block (it already
       has two above its director), two after individuals — each as its precedent. */
    block(V.attorneys.map(a => a.name), W_.attorneyLabel, S.grantor.type === 'company' && signers.length === 1 ? 1 : 2);
    const w = S.witnesses;
    for (let i = 0; i < w.length; i += 2) {
      if (i + 1 < w.length) rows.push(row([0, 1].map(j => cell(false, [s['W.sig'], nm(s['W.name'], norm(w[i + j])), s['W.trail']]))));
      else rows.push(row([cell(true, [lab(s['F.sig'], W_.witnessLabel), nm(s['F.name'], norm(w[i])), s['F.trail']])]));
    }
    return rows.join('');
  }

  /* ── The current forms ("th", "thEn") ─────────────────────────── */
  const isPublic = c => /\(มหาชน\)|มหาชน\s*จำกัด|public\s+(company|co\.)|\bPCL\b|\bPLC\b/i.test(c.name + ' ' + c.nameEn);
  const entityAuto = c => isPublic(c) ? W2.entityPublic : W2.entity;
  const entityEnAuto = c => isPublic(c) ? W2.entityPublicEn : W2.entityEn;
  /* "บริษัท … จำกัด นิติบุคคลประเภทบริษัทจำกัด จดทะเบียนขึ้นตามกฎหมายแห่งราชอาณาจักรไทย
     สำนักงานใหญ่ตั้งอยู่ เลขที่ …" — the words after the name. */
  function companyDetailNew(c) {
    if (c.detail != null) return normText(c.detail);
    return [norm(c.entity != null ? c.entity : entityAuto(c)), norm(c.address) && W2.office + ' ' + withNo(c.address)].filter(Boolean).join(' ');
  }
  function companyDetailNewEn(c) {
    if (c.detailEn != null) return normText(c.detailEn);
    return [norm(c.entityEn != null ? c.entityEn : entityEnAuto(c)), norm(c.addressEn) && W2.officeEn + ' ' + withNoEn(c.addressEn)].filter(Boolean).join(', ');
  }
  function personDetailEn(p) {
    if (p.detailEn != null) return normText(p.detailEn);
    return [
      norm(p.idNo) && W2.holderEn + ' ' + (p.idType === 'passport' ? W2.passportEn : W2.idCardEn) + ' ' + fmtId(p.idNo),
      norm(p.addressEn) && W2.residingEn + ' ' + withNoEn(p.addressEn)
    ].filter(Boolean).join(', ');
  }
  const samePlace = (a, b) => norm(a) === norm(b);
  function deriveNew(S) {
    const g = S.grantor, f = S.facts, V = { form: S.form };
    V.place = S.place != null ? normText(S.place) : W2.place;
    V.placeDefault = samePlace(V.place, W2.place);
    V.placeEn = S.placeEn != null ? normText(S.placeEn) : W2.placeEn;
    V.placeEnDefault = samePlace(V.placeEn, W2.placeEn);
    V.date = S.dateText != null ? norm(S.dateText) : thaiDate(S.dateIso);
    V.dateEn = S.dateTextEn != null ? norm(S.dateTextEn) : englishDate(S.dateIso);
    if (g.type === 'company') {
      const c = g.company;
      const d = companyDetailNew(c), de = companyDetailNewEn(c);
      V.grantor = need(norm(c.name)) + (d ? ' ' + d : '');
      V.grantorEn = need(norm(c.nameEn)) + (de ? ', ' + de : '');
      V.companyName = norm(c.name); V.companyNameEn = norm(c.nameEn);
      V.grantorSigners = c.directors.map(x => norm(x.name));
      V.grantorSignersEn = c.directors.map(x => norm(x.nameEn));
    } else {
      const ps = g.persons;
      V.grantor = W2.self + ' ' + ps.map(p => { const d = personDetail(p); return need(norm(p.name)) + (d ? ' ' + d : ''); }).join(' และ') +
        (norm(g.capacity) ? ' ' + normText(g.capacity) : '');
      V.grantorEn = ps.map(p => { const d = personDetailEn(p); return need(norm(p.nameEn)) + (d ? ', ' + d : ''); }).join(' and ') +
        (norm(g.capacityEn) ? ', ' + normText(g.capacityEn) : '');
      V.grantorSigners = ps.map(p => norm(p.name));
      V.grantorSignersEn = ps.map(p => norm(p.nameEn));
    }
    V.attorneys = S.attorneys.map(a => ({ name: norm(a.name), nameEn: norm(a.nameEn), id: fmtId(a.idNo) }));
    V.counterparty = (f.action != null ? norm(f.action) : W2.action) + need(norm(f.counterparty));
    V.counterpartyEn = (f.actionEn != null ? norm(f.actionEn) : W2.actionEn) + ' ' + need(norm(f.counterpartyEn));
    V.cause = need(normText(f.cause));
    V.causeEn = need(normText(f.causeEn));
    V.stamp = stampDuty(S);
    return V;
  }

  /* The signature table of the current forms, from the precedents' own rows:
     the company's name across the table; a lone signer across the full width
     (the Thai–English precedent's row for its director), others in pairs; an
     empty line above every row but the grantors' first, as in both precedents. */
  function sigRowsNew(F, S, V, bi) {
    const s = F.sig, rows = [];
    const cell = (full, ps) => '<w:tc>' + (full ? F.tcFull : F.tcHalf) + ps.join('') + '</w:tc>';
    const row = cells => F.tr + cells.join('') + '</w:tr>';
    const nm = (p, id, n) => fill(p, id, '(' + (n || BLANK_NAME) + ')');
    const lab = (p, id, l) => put(p, '⟦' + id + '⟧', l);
    /* the witnesses' English line keeps "→Witness" in one run: the tab stays, the word changes */
    const labTab = (p, id, l) => put(p, '<w:t xml:space="preserve">⟦' + id + '⟧</w:t>', '<w:tab/><w:t xml:space="preserve">' + esc(l) + '</w:t>');
    /* one signer: kind H (attorneys), W (witnesses, grantors in pairs) or G1 (full width) */
    function lines(kind, label, labelEn, name, nameEn, lead) {
      const out = [];
      if (lead) out.push(s[(kind === 'G1' ? 'H' : kind) + '.blank']);
      if (kind === 'H') {
        out.push(s['H.sig']); if (bi) out.push(s['H.sigEn']);
      } else if (kind === 'W') {
        out.push(lab(s['W.sig'], 'label', label)); if (bi) out.push(labTab(s['W.sigEn'], 'labelEn', labelEn));
      } else {
        out.push(lab(s['G1.sig'], 'label', label)); if (bi) out.push(lab(s['G1.sigEn'], 'labelEn', labelEn));
      }
      /* a full-width line is centred, so where its middle falls depends on the label */
      const ind = kind === 'G1' ? { [W_.grantorLabel]: 'G1', [W_.attorneyLabel]: 'G1a', [W_.witnessLabel]: 'G1w' }[label] : kind;
      const re = p => p.replace(/⟦IND:\w+⟧/, '⟦IND:' + ind + '⟧');
      out.push(re(nm(s[kind + '.name'], 'name', name)));
      if (bi) out.push(re(nm(s[kind + '.nameEn'], 'nameEn', nameEn)));
      return out;
    }
    function block(kind, names, namesEn, label, labelEn, firstLead) {
      for (let i = 0; i < names.length; i += 2) {
        const lead = i === 0 ? firstLead : true;
        if (i + 1 < names.length) rows.push(row([0, 1].map(j => cell(false, lines(kind, label, labelEn, names[i + j], namesEn[i + j], lead)))));
        else rows.push(row([cell(true, lines('G1', label, labelEn, names[i], namesEn[i], lead))]));
      }
    }
    const signers = V.grantorSigners.length ? V.grantorSigners : [''];
    if (S.grantor.type === 'company') {
      const co = [fill(s['CO.company'], 'company', need(V.companyName))];
      if (bi) co.push(fill(s['CO.companyEn'], 'companyEn', need(V.companyNameEn)));
      rows.push(row([cell(true, co.concat([s['CO.trail']]))]));
    }
    block('W', signers, V.grantorSignersEn, W_.grantorLabel, W2.grantorLabelEn, false);
    block('H', V.attorneys.map(a => a.name), V.attorneys.map(a => a.nameEn), W_.attorneyLabel, W2.attorneyLabelEn, true);
    block('W', S.witnesses.map(norm), S.witnesses.map((w, i) => norm(S.witnessesEn[i])), W_.witnessLabel, W2.witnessLabelEn, true);
    return rows.join('');
  }

  function buildNew(D, S) {
    const P = D.forms && D.forms[S.form];
    if (!P) throw new Error('this build has no "' + S.form + '" form');
    const F = P.frags, G = P.geom || {}, bi = S.form === 'thEn';
    const V = deriveNew(S);
    const parts = [], en = p => { if (bi) parts.push(p); };
    parts.push(F.title); en(F.titleEn);
    parts.push(V.placeDefault ? F.placeDefault : fill(F.place, 'place', V.place));
    en(V.placeEnDefault ? F.placeEnDefault : fill(F.placeEn, 'placeEn', V.placeEn));
    parts.push(fill(F.date, 'date', V.date)); en(F.dateEn && fill(F.dateEn, 'dateEn', V.dateEn));
    parts.push(fill(F.grantor, 'grantor', V.grantor)); en(F.grantorEn && fill(F.grantorEn, 'grantorEn', V.grantorEn));
    parts.push(put(F.attTable, '⟦ROWS⟧', V.attorneys.map((a, i) => {
      let r = put(F.attRow, '⟦no⟧', (i + 1) + '.');
      r = fill(r, 'name', need(a.name));
      if (bi) r = fill(r, 'nameEn', need(a.nameEn));
      return fill(r, 'id', need(a.id));
    }).join('')));
    parts.push(fill(fill(F.intro, 'counterparty', V.counterparty), 'cause', V.cause));
    en(F.introEn && fill(fill(F.introEn, 'counterpartyEn', V.counterpartyEn), 'causeEn', V.causeEn));
    parts.push(F.scope); en(F.scopeEn);
    let n = 0;
    const no = p => put(p, '⟦no⟧', (++n) + '.');
    const extra = k => S.extraClauses.filter(c => c.after === k && norm(c.text)).forEach(c => {
      parts.push(fill(no(F.extraClause), 'TEXT', normText(c.text)));
      en(F.extraClauseEn && fill(F.extraClauseEn, 'TEXT', need(normText(c.textEn))));
    });
    extra(0);
    F.clauses.forEach((p, k) => { parts.push(no(p)); if (bi) parts.push(F.clausesEn[k]); extra(k + 1); });
    parts.push(F.closing); en(F.closingEn);
    parts.push(sigNewPage(S) ? F['sigLead.nextPage'] : F['sigLead.samePage']);
    parts.push(put(F.sigTable, '⟦ROWS⟧', sigRowsNew(F, S, V, bi)));
    parts.push(fill(F.stamp, 'stamp', V.stamp.amount));
    let xml = F.head + parts.join('') + F.tail;
    xml = xml.replace(/⟦IND:(\w+)⟧/g, (m, k) => String(G[k] != null ? G[k] : 0));
    const left = xml.match(/⟦[^⟧]*⟧/g);
    return { xml, state: S, derived: V, report: report(S, V), leftover: left || [] };
  }

  /* ── The document ───────────────────────────────────────────── */
  function build(D, input, opts) {
    MARK = !!(opts && opts.mark);
    try { const S = adoptState(input); return isNew(S) ? buildNew(D, S) : buildDoc(D, S); } finally { MARK = false; }
  }
  function buildDoc(D, input) {
    const S = adoptState(input);
    const F = D.frags, A = D.alt || {}, G = D.geom || {};
    const V = derive(S);
    const parts = [];
    parts.push(F.title);
    parts.push(fill(F.place, 'place', V.place));
    parts.push(fill(F.date, 'date', V.date));
    if (S.grantor.type === 'company') parts.push(fill(F['grantor.company'], 'grantor', V.grantorSegs, A['grantor.company']));
    else parts.push(fill(fill(F['grantor.individual'], 'tail', V.tail), 'grantor', V.grantorSegs, A['grantor.individual']));
    parts.push(put(F.attTable, '⟦ROWS⟧', V.attorneys.map((a, i) =>
      fill(fill(put(F.attRow, '⟦no⟧', (i + 1) + '.'), 'name', a.name), 'id', a.id)).join('')));
    parts.push(fill(fill(fill(F.intro, 'counterparty', V.counterparty),
      'claim', sp(V.claim)), 'termDef', '“' + V.term + '”'));
    parts.push(F.scope);
    const extra = k => S.extraClauses.filter(c => c.after === k && norm(c.text)).map(c => fill(F.extraClause, 'text', normText(c.text)));
    parts.push(...extra(0));
    F.clauses.forEach((p, k) => {
      if (k === 0) p = fill(fill(p, 'court', V.court ? V.court + ' ' : ''), 'term', V.term);
      else p = fill(p, 'term', V.term);
      parts.push(p, ...extra(k + 1));
    });
    parts.push(F.closing);
    parts.push(sigNewPage(S) ? F['sigLead.nextPage'] : F['sigLead.samePage']);
    parts.push(put(F.sigTable, '⟦ROWS⟧', sigRows(F, S, V)));
    parts.push(fill(F.stamp, 'stamp', V.stamp.amount));
    let xml = F.head + parts.join('') + F.tail;
    xml = xml.replace(/⟦IND:(\w+)⟧/g, (m, k) => String(G[k] != null ? G[k] : 0));
    const left = xml.match(/⟦[^⟧]*⟧/g);
    return { xml, state: S, derived: V, report: report(S, V), leftover: left || [] };
  }

  /* ── What the lawyer should be told ─────────────────────────── */
  function report(S, V) {
    if (isNew(S)) return reportNew(S, V);
    const blank = [], warn = [];
    const g = S.grantor;
    if (!V.place) blank.push('ทำที่');
    if (!V.date) blank.push('วันที่');
    if (g.type === 'company') {
      if (!V.companyName) blank.push('ชื่อบริษัทผู้มอบอำนาจ');
      if (!norm(g.company.regNo) && g.company.detail == null) blank.push('ทะเบียนนิติบุคคลเลขที่');
      if (!norm(g.company.address) && g.company.detail == null) blank.push('สำนักงานแห่งใหญ่');
      if (!V.grantorSigners.some(Boolean)) blank.push('กรรมการผู้ลงนาม');
    } else {
      g.persons.forEach((p, i) => {
        const n = ' ' + (i + 1);
        if (!norm(p.name)) blank.push('ชื่อผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.idNo)) blank.push('เลขบัตร/หนังสือเดินทางผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.address)) blank.push('ภูมิลำเนาผู้มอบอำนาจ' + n);
      });
    }
    S.attorneys.forEach((a, i) => { if (!norm(a.name)) blank.push('ชื่อผู้รับมอบอำนาจ ' + (i + 1)); });
    if (!V.counterparty) blank.push('คู่กรณี');
    if (S.facts.claim == null && !norm(S.facts.cause)) blank.push('เหตุที่ฟ้อง (อันเนื่องมาจาก…)');
    if (!V.term) blank.push('ชื่อเรียกเหตุ (“…”)');
    if (!V.court) blank.push('ศาลในข้อ 1');
    const badIds = [];
    S.attorneys.forEach(a => { if (digits(a.idNo).length === 13 && !idValid(a.idNo)) badIds.push(norm(a.name) || a.idNo); });
    if (g.type === 'individual') g.persons.forEach(p => { if (p.idType === 'id' && digits(p.idNo).length === 13 && !idValid(p.idNo)) badIds.push(norm(p.name) || p.idNo); });
    if (g.type === 'company' && g.company.directorIds) g.company.directors.forEach(d => { if (digits(d.idNo).length === 13 && !idValid(d.idNo)) badIds.push(norm(d.name) || d.idNo); });
    S.attorneys.forEach(a => { const d = digits(a.idNo); if (d && d.length !== 13) warn.push('เลขประจำตัวของ ' + (norm(a.name) || 'ผู้รับมอบอำนาจ') + ' ไม่ครบ 13 หลัก'); });
    const empties = S.extraClauses.filter(c => !norm(c.text)).length;
    if (empties) warn.push(empties + ' added clause(s) are empty and were left out');
    return { blank, invalidIds: badIds, warnings: warn };
  }

  function reportNew(S, V) {
    const blank = [], warn = (S.inputNotes || []).slice();
    const g = S.grantor, f = S.facts, bi = S.form === 'thEn';
    const en = (v, label) => { if (bi && !norm(v)) blank.push(label + ' (EN)'); };
    if (!V.place) blank.push('ทำที่');
    if (!V.date) blank.push('วันที่');
    if (bi && V.date && !V.dateEn) blank.push('วันที่ (EN)');
    if (bi && V.place && !V.placeEn) blank.push('ทำที่ (EN)');
    if (g.type === 'company') {
      const c = g.company;
      if (!norm(c.name)) blank.push('ชื่อบริษัทผู้มอบอำนาจ');
      en(c.nameEn, 'ชื่อบริษัทผู้มอบอำนาจ');
      if (c.detail == null && !norm(c.address)) blank.push('สำนักงานใหญ่');
      if (bi && c.detailEn == null) en(c.addressEn, 'สำนักงานใหญ่');
      if (!V.grantorSigners.some(Boolean)) blank.push('กรรมการผู้ลงนาม');
      else if (bi) c.directors.forEach((d, i) => { if (norm(d.name)) en(d.nameEn, 'ชื่อกรรมการ ' + (i + 1)); });
    } else {
      g.persons.forEach((p, i) => {
        const n = ' ' + (i + 1);
        if (!norm(p.name)) blank.push('ชื่อผู้มอบอำนาจ' + n);
        en(p.nameEn, 'ชื่อผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.idNo)) blank.push('เลขบัตร/หนังสือเดินทางผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.address)) blank.push('ภูมิลำเนาผู้มอบอำนาจ' + n);
        if (bi && p.detailEn == null) en(p.addressEn, 'ภูมิลำเนาผู้มอบอำนาจ' + n);
      });
      if (norm(g.capacity)) en(g.capacityEn, 'ในฐานะ');
    }
    S.attorneys.forEach((a, i) => {
      if (!norm(a.name)) blank.push('ชื่อผู้รับมอบอำนาจ ' + (i + 1));
      en(a.nameEn, 'ชื่อผู้รับมอบอำนาจ ' + (i + 1));
      if (!norm(a.idNo)) blank.push('เลขบัตรผู้รับมอบอำนาจ ' + (i + 1));
    });
    if (!norm(f.counterparty)) blank.push('คู่กรณี');
    en(f.counterpartyEn, 'คู่กรณี');
    if (!norm(f.cause)) blank.push('เหตุ (อันเนื่องมาจาก…)');
    en(f.causeEn, 'เหตุ (อันเนื่องมาจาก…)');
    S.extraClauses.forEach((c, i) => { if (norm(c.text)) en(c.textEn, 'ข้อที่เพิ่ม ' + (i + 1)); });
    S.witnesses.forEach((w, i) => { if (norm(w)) en(S.witnessesEn[i], 'พยาน ' + (i + 1)); });
    const badIds = [];
    S.attorneys.forEach(a => { if (digits(a.idNo).length === 13 && !idValid(a.idNo)) badIds.push(norm(a.name) || a.idNo); });
    if (g.type === 'individual') g.persons.forEach(p => { if (p.idType === 'id' && digits(p.idNo).length === 13 && !idValid(p.idNo)) badIds.push(norm(p.name) || p.idNo); });
    S.attorneys.forEach(a => { const d = digits(a.idNo); if (d && d.length !== 13 && !isPlaceholder(a.idNo)) warn.push('เลขประจำตัวของ ' + (norm(a.name) || 'ผู้รับมอบอำนาจ') + ' ไม่ครบ 13 หลัก'); });
    const empties = S.extraClauses.filter(c => !norm(c.text)).length;
    if (empties) warn.push(empties + ' added clause(s) are empty and were left out');
    return { blank, invalidIds: badIds, warnings: warn };
  }

  /* ── File name: "<matter> - หนังสือมอบอำนาจฟ้องคดี <YYYYMMDD>.docx" ── */
  function fileName(S) {
    S = adoptState(S);
    const m = norm(S.matter);
    const d = /^\d{4}-\d{2}-\d{2}$/.test(S.dateIso || '') ? S.dateIso.replace(/-/g, '') : '';
    return (m ? m + ' - ' : '') + (S.form === 'thEn' ? 'POA' : 'หนังสือมอบอำนาจฟ้องคดี') + (d ? ' ' + d : '') + '.docx';
  }
  const safeName = s => String(s).replace(/[\\/:*?"<>|]+/g, ' ').replace(/\s+/g, ' ').trim();

  return {
    build, fill, typeRuns, scriptChunks, adjustRpr,
    blankState, adoptState, fromInput, derive, stampDuty, report,
    fileName: S => safeName(fileName(S)),
    fmtId, idValid, thaiDate, englishDate, companyDetail, personDetail, claimAuto, courtAuto,
    companyDetailNew, companyDetailNewEn, personDetailEn, entityAuto, entityEnAuto, sigNewPage, formKey,
    CLAUSES, CLAUSES_NEW, FORMS, WORDS: W_, WORDS_NEW: W2, BLANK_NAME, PLACEHOLDER
  };
}));
