/* GENERATED by scripts/extract-templates.mjs from litigation-tools/power-of-attorney.html — do not edit here;
   the source is litigation-tools/_build/power-of-attorney/pwa-engine.js. */
/* หนังสือมอบอำนาจให้ฟ้องคดี — the fill engine.
   One file, run as it is by the page (inlined by assemble.py) and by the MCP
   server (copied to mcp-server/src/pwa-engine.cjs by `npm run sync-templates`),
   so a document made in either place is the same document.

   D = the build's data: { frags, alt, geom } (see build_pwa.py, measure.py).
   S = the page's state (blankState). fromInput() maps the MCP's English keys.

   Filling never builds formatting of its own. Each value is typed into the
   run that held the old value: the run keeps its <w:rPr>, and only <w:cs/> is
   set per stretch of text the way Word sets it when you type — on Thai, off on
   Latin letters and digits, spaces and punctuation staying with their
   neighbours. Paragraphs and table rows are the precedents' own, copied whole. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.PWAEngine = factory();
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const MONTHS = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน',
                  'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];
  const THD = '๐๑๒๓๔๕๖๗๘๙';

  /* The fixed words the tool writes when it composes a value itself. They are
     the precedents' own wording (the company and individual files), with one
     spelling fixed in the forum sentence: "องค์กรณ์" → "องค์กร". */
  const W_ = {
    incorporation: 'นิติบุคคลจัดตั้งขึ้นถูกต้องตามกฎหมายแห่งราชอาณาจักรไทย',
    authority: 'กรรมการผู้มีอำนาจลงลายมือชื่อและประทับตราสำคัญกระทำการแทนได้',
    regNo: 'ทะเบียนนิติบุคคลเลขที่',
    office: 'สำนักงานแห่งใหญ่ตั้งอยู่ ณ',
    domicile: 'ภูมิลำเนาอยู่ ณ',
    idCard: 'บัตรประจำตัวประชาชนเลขที่',
    passport: 'หนังสือเดินทางเลขที่',
    dirId: 'ผู้ถือบัตรประจำตัวประชาชนเลขที่',
    forumTail: 'ศาลสถิตยุติธรรมที่มีเขตอำนาจ องค์กร หน่วยงานของรัฐ และ/หรือ พนักงานเจ้าหน้าที่ตลอดจนบุคคลที่เกี่ยวข้องอื่นใด',
    because: 'อันเนื่องมาจาก',
    grantorLabel: 'ผู้มอบอำนาจ',
    attorneyLabel: 'ผู้รับมอบอำนาจ',
    witnessLabel: 'พยาน'
  };

  /* The clauses printed on every document, in order; text as in the template
     (the tool never edits them). Used for the page's list and for reports. */
  const CLAUSES = [
    'ยื่นฟ้องและดำเนินคดีแพ่งและอาญากับคู่กรณีต่อศาล …',
    'เข้าร่วมและดำเนินกระบวนพิจารณาคดีของศาล …',
    'แต่งตั้งทนายความ (มาตรา 62) …',
    'ทำ ลงนาม และรับรองคำแปลภาษาไทย …',
    'เข้าร่วมการเจรจา ไกล่เกลี่ย ประนีประนอมยอมความ …',
    'ให้การ เป็นพยาน ให้ถ้อยคำ … ที่เกี่ยวกับ(เหตุ) …',
    'กระทำการในเรื่องใดๆ ทั้งหมดที่จำเป็นหรือเหมาะสม …',
    'แต่งตั้งผู้รับมอบอำนาจช่วง …'
  ];

  const BLANK_NAME = '______________________________';

  /* ── Text helpers ───────────────────────────────────────────── */
  const norm = s => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
  /* Free text keeps the drafter's own line breaks (a Thai justified line is often
     mended with one) and the space before them; only doubled spaces and the
     spaces at either end go. */
  const normText = s => String(s == null ? '' : s).replace(/\r\n?/g, '\n').replace(/[ \u00A0\t]+/g, ' ').replace(/^ +| +$/g, '');
  /* The space before a value is the precedent's own run and stays; the one
     after is typed with the value — except after a line break, where the
     drafter wanted the line to end. */
  const sp = v => v && v[v.length - 1] !== '\n' ? v + ' ' : v;
  const toArab = s => String(s || '').replace(/[๐-๙]/g, c => String(THD.indexOf(c)));
  const digits = s => toArab(s).replace(/\D/g, '');
  const isPlaceholder = v => /^\(\*.*\)$/.test(String(v == null ? '' : v).trim());

  function fmtId(s) {
    const d = digits(s);
    if (d.length !== 13) return norm(s);
    return [d[0], d.slice(1, 5), d.slice(5, 10), d.slice(10, 12), d[12]].join(' ');
  }
  function idValid(s) {
    const d = digits(s);
    if (d.length !== 13) return false;
    let t = 0; for (let i = 0; i < 12; i++) t += (+d[i]) * (13 - i);
    return (11 - t % 11) % 10 === +d[12];
  }
  function thaiDate(iso) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(iso || '')) return '';
    const [y, m, d] = iso.split('-').map(Number);
    return d + ' ' + MONTHS[m - 1] + ' ' + (y + 543);
  }
  const withNo = a => (a = norm(a)) && !/^เลขที่/.test(a) ? 'เลขที่ ' + a : a;
  const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const put = (xml, mark, s) => xml.split(mark).join(s);

  /* ── Typing into a run ──────────────────────────────────────── */
  const isThai = c => c >= '฀' && c <= '๿';
  const isLatin = c => /[A-Za-z0-9À-ɏ]/.test(c);

  /* Stretches of one script. Spaces and punctuation belong to the stretch they
     sit in (leading ones to the first script after them), as Word does. A
     stretch with no Thai or Latin at all keeps the run exactly as it was. */
  function scriptChunks(text) {
    const out = [];
    let cur = null;
    for (const ch of text) {
      const k = isThai(ch) ? 'T' : isLatin(ch) ? 'L' : null;
      if (!cur) { cur = { k, s: ch }; out.push(cur); continue; }
      if (k === null || k === cur.k) { cur.s += ch; continue; }
      if (cur.k === null) { cur.k = k; cur.s += ch; continue; }
      cur = { k, s: ch }; out.push(cur);
    }
    return out;
  }

  const RPR_AFTER_CS = /<w:(?:em|lang|eastAsianLayout|specVanish|oMath)\b/;
  const RPR_AFTER_HL = /<w:(?:u|effect|bdr|shd|fitText|vertAlign|rtl|cs|em|lang|eastAsianLayout|specVanish|oMath)\b/;
  function insertAt(inner, re, el) {
    const i = inner.search(re);
    return i < 0 ? inner + el : inner.slice(0, i) + el + inner.slice(i);
  }
  function adjustRpr(rpr, script, highlight) {
    if (script === null && !highlight) return rpr;
    let inner = rpr ? rpr.replace(/^<w:rPr>/, '').replace(/<\/w:rPr>$/, '') : '';
    if (script !== null) {
      inner = inner.replace(/<w:cs(?: w:val="[^"]*")?\/>/g, '');
      if (script === 'T') inner = insertAt(inner, RPR_AFTER_CS, '<w:cs/>');
    }
    if (highlight && !/<w:highlight\b/.test(inner)) inner = insertAt(inner, RPR_AFTER_HL, '<w:highlight w:val="yellow"/>');
    return inner ? '<w:rPr>' + inner + '</w:rPr>' : '';
  }
  function content(s) {
    let out = '', buf = '';
    const flush = () => { if (buf) { out += '<w:t xml:space="preserve">' + esc(buf) + '</w:t>'; buf = ''; } };
    for (const ch of s) {
      if (ch === '\n') { flush(); out += '<w:br/>'; }
      else if (ch === '\t') { flush(); out += '<w:tab/>'; }
      else buf += ch;
    }
    flush();
    return out;
  }
  function typeRuns(open, rpr, text, highlight) {
    return scriptChunks(text).map(c => open + adjustRpr(rpr, c.k, highlight) + content(c.s) + '</w:r>').join('');
  }

  /* Replace the run holding ⟦id⟧ with the value typed into it. A value is a
     string, or a list of { text, alt } where alt picks the other run properties
     the build kept for this marker (the grantor's name in bold). An empty
     value removes the run. "(*…)" marks a deliberate blank: highlighted. */
  let MARK = false;       // preview only: typed runs carry data-v="1" so the page can show them
  function fill(xml, id, value, altRpr) {
    const mark = '⟦' + id + '⟧';
    let i;
    while ((i = xml.indexOf(mark)) !== -1) {
      const s = Math.max(xml.lastIndexOf('<w:r>', i), xml.lastIndexOf('<w:r ', i));
      const e = xml.indexOf('</w:r>', i) + 6;
      const run = xml.slice(s, e);
      const open = MARK ? '<w:r data-v="1">' : run.slice(0, run.indexOf('>') + 1);
      const m = run.match(/<w:rPr>[\s\S]*?<\/w:rPr>/);
      const rpr = m ? m[0] : '';
      const segs = Array.isArray(value) ? value : [{ text: value }];
      const out = segs.map(g => {
        const t = String(g.text == null ? '' : g.text);
        return typeRuns(open, g.alt ? altRpr : rpr, t, isPlaceholder(g.ph != null ? g.ph : t));
      }).join('');
      xml = xml.slice(0, s) + out + xml.slice(e);
    }
    return xml;
  }

  /* ── State ──────────────────────────────────────────────────── */
  const blankPerson = () => ({ name: '', idType: 'id', idNo: '', address: '', detail: null });
  const blankDirector = () => ({ name: '', idNo: '' });
  const blankAttorney = () => ({ name: '', idNo: '' });
  function blankState() {
    return {
      kind: 'litigation',
      matter: '',
      place: '', dateIso: '', dateText: null,
      grantor: {
        type: 'company',
        company: { name: '', incorporation: W_.incorporation, regNo: '', address: '',
                   directors: [blankDirector()], directorIds: false, authority: W_.authority, detail: null },
        persons: [blankPerson()],
        capacity: ''
      },
      attorneys: [blankAttorney()],
      facts: { counterparty: '', forums: [''], bodies: [], cause: '', term: '', claim: null, court: null },
      extraClauses: [],
      witnesses: ['', ''],
      sigNewPage: true,
      stamp: { principals: null, amount: null }
    };
  }
  function adoptState(st) {
    st = st || {};
    const b = blankState();
    const g = st.grantor || {};
    const out = Object.assign(b, st);
    out.grantor = Object.assign(blankState().grantor, g);
    out.grantor.company = Object.assign(blankState().grantor.company, g.company || {});
    out.grantor.company.directors = (out.grantor.company.directors && out.grantor.company.directors.length
      ? out.grantor.company.directors : [blankDirector()]).map(d => Object.assign(blankDirector(), d));
    out.grantor.persons = (g.persons && g.persons.length ? g.persons : [blankPerson()]).map(p => Object.assign(blankPerson(), p));
    if (out.grantor.type !== 'individual') out.grantor.type = 'company';
    out.attorneys = (st.attorneys && st.attorneys.length ? st.attorneys : [blankAttorney()]).map(a => Object.assign(blankAttorney(), a));
    out.facts = Object.assign(blankState().facts, st.facts || {});
    if (!Array.isArray(out.facts.forums) || !out.facts.forums.length) out.facts.forums = [''];
    if (!Array.isArray(out.facts.bodies)) out.facts.bodies = [];
    out.extraClauses = (st.extraClauses || []).map(c => ({ after: clampAfter(c.after), text: c.text || '' }));
    out.witnesses = Array.isArray(st.witnesses) ? st.witnesses.map(w => w || '') : ['', ''];
    out.stamp = Object.assign(blankState().stamp, st.stamp || {});
    out.sigNewPage = st.sigNewPage !== false;
    return out;
  }
  const clampAfter = n => Math.max(0, Math.min(CLAUSES.length, parseInt(n, 10) || 0));

  /* The MCP's English keys → state. Absent means "compose it"; "" means blank. */
  function fromInput(a) {
    a = a || {};
    const S = blankState();
    const g = a.grantor || {};
    S.matter = a.matter || '';
    S.place = a.place || '';
    S.dateIso = a.date || '';
    if (a.dateText != null) S.dateText = a.dateText;
    S.grantor.type = g.type === 'individual' ? 'individual' : 'company';
    if (g.company) {
      const c = g.company, T = S.grantor.company;
      T.name = c.name || '';
      if (c.incorporation != null) T.incorporation = c.incorporation;
      T.regNo = c.registrationNumber || '';
      T.address = c.headOfficeAddress || '';
      if (c.directors && c.directors.length) T.directors = c.directors.map(d => ({ name: d.name || '', idNo: d.idNumber || '' }));
      T.directorIds = !!(c.directors || []).some(d => d.idNumber);
      if (c.authorityWording != null) T.authority = c.authorityWording;
      if (c.descriptionOverride != null) T.detail = c.descriptionOverride;
    }
    if (g.persons && g.persons.length) {
      S.grantor.persons = g.persons.map(p => ({ name: p.name || '', idType: p.idType === 'passport' ? 'passport' : 'id',
        idNo: p.idNumber || '', address: p.address || '', detail: p.descriptionOverride != null ? p.descriptionOverride : null }));
    }
    S.grantor.capacity = g.capacity || '';
    if (a.attorneys && a.attorneys.length) S.attorneys = a.attorneys.map(x => ({ name: x.name || '', idNo: x.idNumber || '' }));
    const f = a.matterFacts || {};
    S.facts.counterparty = f.counterparty || '';
    S.facts.forums = f.courts && f.courts.length ? f.courts.slice() : [''];
    S.facts.bodies = f.otherBodies ? f.otherBodies.slice() : [];
    S.facts.cause = f.cause || '';
    S.facts.term = f.definedTerm || '';
    if (f.narrativeOverride != null) S.facts.claim = f.narrativeOverride;
    if (f.clause1CourtsOverride != null) S.facts.court = f.clause1CourtsOverride;
    S.extraClauses = (a.extraClauses || []).map(c => ({ after: clampAfter(c.afterClause), text: c.text || '' }));
    if (Array.isArray(a.witnesses)) S.witnesses = a.witnesses.map(w => w || '');
    if (a.signaturesOnNextPage != null) S.sigNewPage = !!a.signaturesOnNextPage;
    if (a.stampDuty) {
      if (a.stampDuty.principals != null) S.stamp.principals = a.stampDuty.principals;
      if (a.stampDuty.amountOverride != null) S.stamp.amount = a.stampDuty.amountOverride;
    }
    return adoptState(S);
  }

  /* ── What the document says, worked out from the state ──────── */
  function companyDetail(c) {
    if (c.detail != null) return normText(c.detail);
    const dirs = c.directors.filter(d => norm(d.name));
    const who = dirs.map(d => norm(d.name) + (c.directorIds && norm(d.idNo) ? ' ' + W_.dirId + ' ' + fmtId(d.idNo) : '')).join(' และ');
    return [
      norm(c.incorporation),
      norm(c.regNo) && W_.regNo + ' ' + norm(c.regNo),
      norm(c.address) && W_.office + ' ' + withNo(c.address),
      who && 'โดย' + who + (norm(c.authority) ? ' ' + norm(c.authority) : '')
    ].filter(Boolean).join(' ');
  }
  function personDetail(p) {
    if (p.detail != null) return normText(p.detail);
    return [
      norm(p.idNo) && (p.idType === 'passport' ? W_.passport : W_.idCard) + ' ' + fmtId(p.idNo),
      norm(p.address) && W_.domicile + ' ' + withNo(p.address)
    ].filter(Boolean).join(' ');
  }
  function claimAuto(f) {
    const where = f.forums.concat(f.bodies).map(norm).filter(Boolean);
    return 'ต่อ' + (where.length ? where.join(' ') + ' หรือ' : '') + W_.forumTail + ' ' + W_.because + normText(f.cause);
  }
  const courtAuto = f => f.forums.map(norm).filter(Boolean).join(' ').replace(/^ศาล\s*/, '');

  function stampDuty(S) {
    const n = Math.max(1, S.attorneys.length);
    const autoP = S.grantor.type === 'individual' ? Math.max(1, S.grantor.persons.filter(p => norm(p.name)).length || 1) : 1;
    const principals = S.stamp.principals != null && S.stamp.principals !== '' ? Math.max(1, parseInt(S.stamp.principals, 10) || 1) : autoP;
    const auto = 30 * n * principals;
    const amt = S.stamp.amount != null && String(S.stamp.amount).trim() !== '' ? String(S.stamp.amount).trim() : null;
    return {
      item: n > 1 ? '7(ค)' : '7(ข)',
      attorneys: n, principals, principalsAuto: S.stamp.principals == null || S.stamp.principals === '',
      perPerson: 30, auto,
      amount: amt != null ? amt : String(auto), overridden: amt != null
    };
  }

  function derive(S) {
    const g = S.grantor, f = S.facts, V = {};
    V.place = normText(S.place);
    V.date = S.dateText != null ? norm(S.dateText) : thaiDate(S.dateIso);
    if (g.type === 'company') {
      const c = g.company;
      const d = companyDetail(c);
      /* The company precedent types the space after the name in bold. */
      V.grantorSegs = [{ text: norm(c.name) && d ? norm(c.name) + ' ' : norm(c.name), alt: true }, { text: d }];
      V.companyName = norm(c.name);
      V.grantorSigners = c.directors.map(d => norm(d.name));
    } else {
      const ps = g.persons;
      V.grantorSegs = [];
      ps.forEach((p, i) => {
        V.grantorSegs.push({ text: norm(p.name), alt: true });
        const d = personDetail(p);
        V.grantorSegs.push({ text: (d ? ' ' + d : '') + (i < ps.length - 1 ? ' และ' : '') });
      });
      V.tail = sp(normText(g.capacity));
      V.grantorSigners = ps.map(p => norm(p.name));
    }
    V.attorneys = S.attorneys.map(a => ({ name: norm(a.name), id: fmtId(a.idNo) }));
    V.counterparty = norm(f.counterparty);
    V.claim = f.claim != null ? normText(f.claim) : claimAuto(f);
    V.court = f.court != null ? norm(f.court).replace(/^ศาล\s*/, '') : courtAuto(f);
    V.term = norm(f.term);
    V.stamp = stampDuty(S);
    return V;
  }

  /* ── The signature table ────────────────────────────────────── */
  /* Rows of two, one signer per half; an odd one out gets the full width,
     centred — how every precedent lays it out. A lone grantor sits alone at
     the top (a company's name above its director). Two blank lines before the
     first attorneys' row, one after every row, as in the precedents. */
  function sigRows(F, S, V) {
    const s = F.sig, rows = [];
    const cell = (full, ps) => '<w:tc>' + (full ? F.tcFull : F.tcHalf) + ps.join('') + '</w:tc>';
    const row = cells => F.tr + cells.join('') + '</w:tr>';
    const nm = (p, n) => fill(p, 'name', n || BLANK_NAME);
    const lab = (p, l) => put(p, '⟦label⟧', l);                 // a fixed word, in the run that held it
    const rep = (p, k) => Array.from({ length: k }, () => p);
    function block(names, label, firstLead) {
      for (let i = 0; i < names.length; i += 2) {
        const lead = i === 0 ? firstLead : 0;
        if (i + 1 < names.length) {
          rows.push(row([0, 1].map(j => cell(false,
            rep(s['H.blank'], lead).concat([lab(s['H.sig'], label), nm(s['H.name'], names[i + j]), s['H.trail']])))));
        } else {
          rows.push(row([cell(true,
            rep(s['F.trail'], lead).concat([lab(s['F.sig'], label), nm(s['F.name'], names[i]), s['F.trail']]))]));
        }
      }
    }
    const signers = V.grantorSigners.length ? V.grantorSigners : [''];
    if (S.grantor.type === 'company') {
      const co = fill(s['GC.company'], 'company', V.companyName);
      if (signers.length === 1) rows.push(row([cell(true, [co, s['GC.blank'], s['GC.blank'], s['GC.sig'], nm(s['GC.name'], signers[0])])]));
      else { rows.push(row([cell(true, [co])])); block(signers, W_.grantorLabel, 2); }
    } else if (signers.length === 1) {
      rows.push(row([cell(true, [s['GI.blank'], s['GI.sig'], nm(s['GI.name'], signers[0])])]));
    } else block(signers, W_.grantorLabel, 1);
    /* Blank lines above the attorneys: one after a company's block (it already
       has two above its director), two after individuals — each as its precedent. */
    block(V.attorneys.map(a => a.name), W_.attorneyLabel, S.grantor.type === 'company' && signers.length === 1 ? 1 : 2);
    const w = S.witnesses;
    for (let i = 0; i < w.length; i += 2) {
      if (i + 1 < w.length) rows.push(row([0, 1].map(j => cell(false, [s['W.sig'], nm(s['W.name'], norm(w[i + j])), s['W.trail']]))));
      else rows.push(row([cell(true, [lab(s['F.sig'], W_.witnessLabel), nm(s['F.name'], norm(w[i])), s['F.trail']])]));
    }
    return rows.join('');
  }

  /* ── The document ───────────────────────────────────────────── */
  function build(D, input, opts) {
    MARK = !!(opts && opts.mark);
    try { return buildDoc(D, input); } finally { MARK = false; }
  }
  function buildDoc(D, input) {
    const S = adoptState(input);
    const F = D.frags, A = D.alt || {}, G = D.geom || {};
    const V = derive(S);
    const parts = [];
    parts.push(F.title);
    parts.push(fill(F.place, 'place', V.place));
    parts.push(fill(F.date, 'date', V.date));
    if (S.grantor.type === 'company') parts.push(fill(F['grantor.company'], 'grantor', V.grantorSegs, A['grantor.company']));
    else parts.push(fill(fill(F['grantor.individual'], 'tail', V.tail), 'grantor', V.grantorSegs, A['grantor.individual']));
    parts.push(put(F.attTable, '⟦ROWS⟧', V.attorneys.map((a, i) =>
      fill(fill(put(F.attRow, '⟦no⟧', (i + 1) + '.'), 'name', a.name), 'id', a.id)).join('')));
    parts.push(fill(fill(fill(F.intro, 'counterparty', V.counterparty),
      'claim', sp(V.claim)), 'termDef', '“' + V.term + '”'));
    parts.push(F.scope);
    const extra = k => S.extraClauses.filter(c => c.after === k && norm(c.text)).map(c => fill(F.extraClause, 'text', normText(c.text)));
    parts.push(...extra(0));
    F.clauses.forEach((p, k) => {
      if (k === 0) p = fill(fill(p, 'court', V.court ? V.court + ' ' : ''), 'term', V.term);
      else p = fill(p, 'term', V.term);
      parts.push(p, ...extra(k + 1));
    });
    parts.push(F.closing);
    parts.push(S.sigNewPage ? F['sigLead.nextPage'] : F['sigLead.samePage']);
    parts.push(put(F.sigTable, '⟦ROWS⟧', sigRows(F, S, V)));
    parts.push(fill(F.stamp, 'stamp', V.stamp.amount));
    let xml = F.head + parts.join('') + F.tail;
    xml = xml.replace(/⟦IND:(\w+)⟧/g, (m, k) => String(G[k] != null ? G[k] : 0));
    const left = xml.match(/⟦[^⟧]*⟧/g);
    return { xml, state: S, derived: V, report: report(S, V), leftover: left || [] };
  }

  /* ── What the lawyer should be told ─────────────────────────── */
  function report(S, V) {
    const blank = [], warn = [];
    const g = S.grantor;
    if (!V.place) blank.push('ทำที่');
    if (!V.date) blank.push('วันที่');
    if (g.type === 'company') {
      if (!V.companyName) blank.push('ชื่อบริษัทผู้มอบอำนาจ');
      if (!norm(g.company.regNo) && g.company.detail == null) blank.push('ทะเบียนนิติบุคคลเลขที่');
      if (!norm(g.company.address) && g.company.detail == null) blank.push('สำนักงานแห่งใหญ่');
      if (!V.grantorSigners.some(Boolean)) blank.push('กรรมการผู้ลงนาม');
    } else {
      g.persons.forEach((p, i) => {
        const n = ' ' + (i + 1);
        if (!norm(p.name)) blank.push('ชื่อผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.idNo)) blank.push('เลขบัตร/หนังสือเดินทางผู้มอบอำนาจ' + n);
        if (p.detail == null && !norm(p.address)) blank.push('ภูมิลำเนาผู้มอบอำนาจ' + n);
      });
    }
    S.attorneys.forEach((a, i) => { if (!norm(a.name)) blank.push('ชื่อผู้รับมอบอำนาจ ' + (i + 1)); });
    if (!V.counterparty) blank.push('คู่กรณี');
    if (S.facts.claim == null && !norm(S.facts.cause)) blank.push('เหตุที่ฟ้อง (อันเนื่องมาจาก…)');
    if (!V.term) blank.push('ชื่อเรียกเหตุ (“…”)');
    if (!V.court) blank.push('ศาลในข้อ 1');
    const badIds = [];
    S.attorneys.forEach(a => { if (digits(a.idNo).length === 13 && !idValid(a.idNo)) badIds.push(norm(a.name) || a.idNo); });
    if (g.type === 'individual') g.persons.forEach(p => { if (p.idType === 'id' && digits(p.idNo).length === 13 && !idValid(p.idNo)) badIds.push(norm(p.name) || p.idNo); });
    if (g.type === 'company' && g.company.directorIds) g.company.directors.forEach(d => { if (digits(d.idNo).length === 13 && !idValid(d.idNo)) badIds.push(norm(d.name) || d.idNo); });
    S.attorneys.forEach(a => { const d = digits(a.idNo); if (d && d.length !== 13) warn.push('เลขประจำตัวของ ' + (norm(a.name) || 'ผู้รับมอบอำนาจ') + ' ไม่ครบ 13 หลัก'); });
    const empties = S.extraClauses.filter(c => !norm(c.text)).length;
    if (empties) warn.push(empties + ' added clause(s) are empty and were left out');
    return { blank, invalidIds: badIds, warnings: warn };
  }

  /* ── File name: "<matter> - หนังสือมอบอำนาจฟ้องคดี <YYYYMMDD>.docx" ── */
  function fileName(S) {
    S = adoptState(S);
    const m = norm(S.matter);
    const d = /^\d{4}-\d{2}-\d{2}$/.test(S.dateIso || '') ? S.dateIso.replace(/-/g, '') : '';
    return (m ? m + ' - ' : '') + 'หนังสือมอบอำนาจฟ้องคดี' + (d ? ' ' + d : '') + '.docx';
  }
  const safeName = s => String(s).replace(/[\\/:*?"<>|]+/g, ' ').replace(/\s+/g, ' ').trim();

  return {
    build, fill, typeRuns, scriptChunks, adjustRpr,
    blankState, adoptState, fromInput, derive, stampDuty, report,
    fileName: S => safeName(fileName(S)),
    fmtId, idValid, thaiDate, companyDetail, personDetail, claimAuto, courtAuto,
    CLAUSES, WORDS: W_, BLANK_NAME
  };
}));
